### ISSUE TITLE
Distance is shown incorrectly

### ISSUE THREAD

**Issue by Veldkornet** [snicker/zwift_hass#1]
Version: cacbb4a

It looks as though the decimal is in the incorrect place for the distance.

At 12.8 km in Zwift, it’s shown as 12800.0 km in HomeAssistant

**Comment by Veldkornet** [comment]
Example:
![CE565231-3EA9-4AC6-9E2F-F53383A6AD4D](https://user-images.githubusercontent.com/10297361/70392853-49d2a180-19e4-11ea-83b1-f9195951bc92.jpeg)
![Uploading ED6C5027-A5DE-4403-9CDA-8D114B29451F.jpeg…]()

**Comment by snicker** [comment]
@Veldkornet without researching how this is affected with metric vs imperial units (which is based on user configuration) I have simply changed the unit for the sensor to meters rather than kilometers. If you'd like to see KM, please use a template sensor to divide by 1000.
