### ISSUE TITLE
Limit value to 0 decimals

### ISSUE THREAD

**Issue by adas4190** [snicker/zwift_hass#2]
as abowe, is there a way to do it?

Thank You

**Comment by snicker** [comment]
You can do this with a template sensor. If truly necessary, could you tell me which sensors should have their values rounded?

**Comment by mountainsandcode** [comment]
I can confirm this one - definitely seeing it on altitude where this is the starting value for a route in NYC world

![image](https://user-images.githubusercontent.com/26942220/103437252-afb04d80-4c25-11eb-9282-a8ec383637b7.png)

I'd propose rounding altitude to 1 decimal (the default value set is 0.0 anyway) to begin with, I'll keep an eye out for other values as well
