### ISSUE TITLE
HASS Supervised HACS not showing - Invalid repository

### ISSUE THREAD

**Issue by gunty99** [snicker/zwift_hass#26]
One of my most important integrations. 
It drives automations for fans, phone muting, outdoor lighting, discord notifications etc etc...
Moved from a synology docker install to Blue running supervised, although listed as a default repo it doesnt show and when I try to add if gives this in the logs and suggests to report it here.

Thanks
Dennis

21-08-24 15:09:53 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/snicker/zwift_hass repository
21-08-24 15:09:53 ERROR (MainThread) [supervisor.store] https://github.com/snicker/zwift_hass is not a valid add-on repository
21-08-24 15:09:53 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / a25c620f
21-08-24 15:09:53 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / a25c620f
21-08-24 15:09:54 WARNING (MainThread) [supervisor.store.data] No repository information exists at /data/addons/git/a25c620f
21-08-24 15:09:54 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 0 new - 0 remove
21-08-24 15:09:54 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: a25c620f
21-08-24 15:09:54 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/snicker/zwift_hass

**Comment by gunty99** [comment]
manually copying to custom_components

Logger: custom_components.zwift.sensor
Source: custom_components/zwift/sensor.py:324
Integration: zwift (documentation)
First occurred: 9:03:41 PM (1 occurrences)
Last logged: 9:03:41 PM

Could not create Zwift sensor named 'Zwift'!
Traceback (most recent call last):
  File "/config/custom_components/zwift/sensor.py", line 123, in async_setup_platform
    await zwift_data._connect()
  File "/config/custom_components/zwift/sensor.py", line 324, in _connect
    from zwift import Client as ZwiftClient
ImportError: cannot import name 'Client' from 'zwift' (/config/zwift/__init__.py)

**Comment by snicker** [comment]
This is not an addon, and can only be installed manually or from HACs. You will need to install `zwift_client` =0.2.0 for this custom component if installing manually.
