### ISSUE TITLE
Zwift is more aggressively throttling requests with 429 errors

### ISSUE THREAD

**Issue by snicker** [snicker/zwift_hass#28]
Per forum post on 11/9:
https://community.home-assistant.io/t/zwift-sensor-component-feedback-and-testers-needed/87512/230

planned fix is to increase interval to 2 seconds while online instead of 1 second.

mid term: allow this to be configured in the integration options

long term: rely on client to client communication on local network

**Comment by snicker** [comment]
This is fixed in https://github.com/snicker/zwift_hass/releases/tag/v3.2.4. Leaving issue open in case it does not resolve for all users. will close in 7 days.

**Comment by snicker** [comment]
Closing issue as resolved after no further reports.

**Comment by snicker** [comment]
re-opening as this has become a bit of a problem again for me personally!

I have updated to https://github.com/snicker/zwift_hass/releases/tag/v3.2.5 which will automatically increase the update intervals by 0.25s each time the server throttles the client. A warning will be logged, indicating what the interval has increased to. Please report your values in this thread.

**Comment by Fleshi1981** [comment]
I have the same problem again, see below for the log:

-----------------------

This error originated from a custom integration.

Logger: custom_components.zwift.sensor
Source: custom_components/zwift/sensor.py:361
Integration: zwift (documentation)
First occurred: 19:58:51 (52 occurrences)
Last logged: 20:44:49

something went wrong in Zwift python library - 429 - Too Many Requests while updating zwift sensor for player 4431663
Traceback (most recent call last):
  File "/config/custom_components/zwift/sensor.py", line 361, in update
    player_state = world.player_status(player_id)
  File "/usr/local/lib/python3.9/site-packages/zwift/world.py", line 24, in player_status
    buffer = self.request.protobuf(
  File "/usr/local/lib/python3.9/site-packages/zwift/request.py", line 44, in protobuf
    raise RequestException("{} - {}".format(
zwift.error.RequestException: 429 - Too Many Requests

**Comment by snicker** [comment]
please update to the latest version, as mentioned above the integration will now dynamically increase the delay between updates if the server is throttling.

**Comment by Fleshi1981** [comment]
> please update to the latest version, as mentioned above the integration will now dynamically increase the delay between updates if the server is throttling. 
> 
> > On Feb 11, 2022, at 12:14 PM, Fleshi1981 ***@***.***> wrote:
> > 
> > ﻿
> > I have the same problem again, see below for the log:
> > 
> > This error originated from a custom integration.
> > 
> > Logger: custom_components.zwift.sensor
> > Source: custom_components/zwift/sensor.py:361
> > Integration: zwift (documentation)
> > First occurred: 19:58:51 (52 occurrences)
> > Last logged: 20:44:49
> > 
> > something went wrong in Zwift python library - 429 - Too Many Requests while updating zwift sensor for player 4431663
> > Traceback (most recent call last):
> > File "/config/custom_components/zwift/sensor.py", line 361, in update
> > player_state = world.player_status(player_id)
> > File "/usr/local/lib/python3.9/site-packages/zwift/world.py", line 24, in player_status
> > buffer = self.request.protobuf(
> > File "/usr/local/lib/python3.9/site-packages/zwift/request.py", line 44, in protobuf
> > raise RequestException("{} - {}".format(
> > zwift.error.RequestException: 429 - Too Many Requests
> > 
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > Triage notifications on the go with GitHub Mobile for iOS or Android. 
> > You are receiving this because you modified the open/close state.
> 

Thanks 👍 and sorry didn't saw the update. 🙂

**Comment by Fleshi1981** [comment]
> > please update to the latest version, as mentioned above the integration will now dynamically increase the delay between updates if the server is throttling.
> 
> Thanks 👍 and sorry didn't saw the update. 🙂

I cycled yesterday and there weren't any problems anymore, thanks for the fix 👍🙂

**Comment by snicker** [comment]
Closing again as the latest automatic throttling seems to have resolved most users' issues.
