### ISSUE TITLE
Binary sensor should be on/off instead of True/False

### ISSUE THREAD

**Issue by dc31xx** [snicker/zwift_hass#32]
Although the [docs](https://www.home-assistant.io/integrations/binary_sensor/) state that `true`/`false` is an option:

> For example, a binary sensor for a window may report a value of open or closed, a switch on or off, a condition true or false.

It is almost always `on`/`off` (check the occupancy device class for example). Also the casing is never capitalized (`true`/`false` instead of `True`/`False`).

**Comment by snicker** [comment]
Could you elaborate? in code, the state should always be represented as Boolean values for binary sensors when reporting the state. When displayed in the UI, it is based on the device class.
