### ISSUE TITLE
Bug: Inaccurate data: not refreshing on latest activity

### ISSUE THREAD

**Issue by tylerwmarrs** [snicker/zwift_hass#36]
This morning I left the game loaded without any movement to turn on the fan etc. Zwift starts collecting data on you as soon as you launch a game. Later they do some post processing to clean up "idle time" and adjust the statistics. I noticed that this plugin doesn't refresh activity data that it already captured. This could result in incorrect information.

# How to reproduce
1. launch zwift
2. go into a route
3. don't move for a few minutes
4. start pedaling as you normally would

Once the plugin fetches the data, you'll see the "duration" being inclusive of the time you sat. This is because Zwift includes this data initially. Wait maybe 2-3 hours and check Zwift feed. Compare it against the fetched data.

**Comment by snicker** [comment]
realize this is quite an old issue, but I don't believe the `zwift-client` library has any control over this.
