### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by lukes-ha** [snicker/zwift_hass#46]
I have tried to set up this integration.
But nothing is happing, I don't have a new entity.

So my question is: does it still work, or did I a mistake?

Thanks

**Comment by arniebarni** [comment]
Works for me, and I have just recently added it. After adding the integration make sure to update your `configuration.yaml` according to [https://github.com/snicker/zwift_hass#installation](https://github.com/snicker/zwift_hass#installation). Then restart. You may want to search the developer tools for any entities with "zwift" in the name and create template sensors for your needs.

Cheers

Arne

**Comment by brianacox** [comment]
> I have tried to set up this integration. But nothing is happing, I don't have a new entity.
> 
> So my question is: does it still work, or did I a mistake?
> 
> Thanks

Did you get it working ?    I've been using the interface for Cycling for a while, without any problems, and went (today) to look at adding Running....  I have lights that change colour according to speed / heart rate.... but I failed... but then realised that the cycling interface didn't appear to be working.   The Apple TV, since the last update, has been a bit of a pain, needing to be reset from time to time, so that might be my issue.....  but interested if you or others have experienced issues in the last couple of weeks?

**Comment by lukes-ha** [comment]
Hi,

I added the integration to the config, and restarted. But there isn't a new entity. 
I added this to my sensors:
`#zwift
    - platform: zwift
      username: XXX@gmail.com
      password: Passwort
      players:
        - XXXXXXX`

Did I made a mistake?

Thanks

**Comment by arniebarni** [comment]
If in proper yaml format that looks good. It would tell you otherwise during restart, I suppose.
Have you checked the logs? Maybe wrong credentials, in that case you'd find something like:
```
Exception: Zwift authorization failed: {'error': 'invalid_grant', 'error_description': 'Invalid user credentials'}
```

**Comment by piotr0777** [comment]
I can't get the plugin to work. After adding zwift integration configuration in configuration.yaml, I run the configuration test in developer tools to see if nothing obstructs the proper boot. Whenever the zwift configuration is added, the configuration test in developer tools gets stuck with no result, spinning all the time. Does anyone have the same issue?

**Comment by cagnulein** [comment]
it's still work, confirmed. maybe share a debug log?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 18 feb 2024 alle 11:05 piotr0777 ***@***.***>
ha scritto:

**Comment by piotr0777** [comment]
It works! Very cool integration! It seems like my HASS just needed a reboot. After the reboot I no longer had any issues with validating the configuration in developer tools.

**Comment by BambamNZ** [comment]
I just installed the integration - one thing I noticed, it did not like the fact that I have a space in my password. 
Did not try and wrap it with quotations easier to update password without spaces and worked perfectly !!!
