### ISSUE TITLE
display latest_activity_image URL in dashboard?

### ISSUE THREAD

**Issue by martin-ef** [snicker/zwift_hass#48]
First: Thank you for this awesome add-on!

My problem: I want to display the URL from sensor.zwift_online_xxx > latest_activity > primaryImageUrl on my dashboard. I know this is not primarily a problem of this add-on but maybe someone here can help me?

Thanks, Martin

**Comment by cagnulein** [comment]
@martin-ef did you achieve this?

**Comment by martin-ef** [comment]
Yes, I did. I installed a „generic camera“ and then added an entity using the URL you can find in the sensor.

![Zwift_genericcamera](https://github.com/snicker/zwift_hass/assets/98596807/b5ecce81-0aa0-4207-9555-f7fbf41004dd)

Hope this helps. FYI: The resolution of the image is pretty low. works fine on a phone, not so much on a huge monitor.
